apiVersion: v1 
kind: Pod 
metadata: 
  name: node-selector
  labels: 
    purpose: "selector-demo"
spec: 
  nodeSelector: 
    topology.ebs.csi.aws.com/zone: us-east-1c 
  containers: 
  - name: nginx 
    image: