apiVersion: v1 
kind: Pod 
metadata: 
  name: tolarations
  labels: 
    purpose: "tolarations-demo"
spec: 
  nodeSelector: 
    topology.ebs.csi.aws.com/zone: us-east-1b
  containers: 
  - name: nginx 
    image: nginx 
  tolarations: 
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"
   